version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    container_name: weather_container
    environment:
      - NODE_ENV=development
      
      