version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/app.js
      - ${PWD}/index.html
      - ${PWD}/styles.css
    container_name: weather_container
    environment:
      - NODE_ENV=development
      
      
